apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deprecated-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deprecated-app
  template:
    metadata:
      labels:
        app: deprecated-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
